const flight = {
  flight_number: 112,
  mission_name: 'USCV-1 (NASA Crew Flight 1)',
  mission_id: ['EE86F74'],
  launch_year: '2021',
  launch_date_unix: 1609459200,
  launch_date_utc: '2021-01-01T00:00:00.000Z',
  launch_date_local: '2020-12-31T19:00:00-05:00',
  is_tentative: true,
  tentative_max_precision: 'month',
  tbd: false,
  launch_window: null,
  rocket:
  {
    rocket_id: 'falcon9',
    rocket_name: 'Falcon 9',
    rocket_type: 'FT',
    first_stage: { cores: [Array] },
    second_stage: { block: 5, payloads: [Array] },
    fairings: null,
  },
  ships: [],
  telemetry: { flight_club: null },
  launch_site:
  {
    site_id: 'ksc_lc_39a',
    site_name: 'KSC LC 39A',
    site_name_long: 'Kennedy Space Center Historic Launch Complex 39A',
  },
  launch_success: null,
  links:
  {
    mission_patch: null,
    mission_patch_small: null,
    reddit_campaign: null,
    reddit_launch: null,
    reddit_recovery: null,
    reddit_media: null,
    presskit: null,
    article_link: null,
    wikipedia: null,
    video_link: null,
    youtube_id: null,
    flickr_images: [],
  },
  details: null,
  upcoming: true,
  static_fire_date_utc: null,
  static_fire_date_unix: null,
  timeline: null,
  crew: [],
};
